source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'SGYKVCSafeNSObject_Tests', :exclusive => true do
  pod 'SGYKVCSafeNSObject', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
