use_frameworks!

target 'SGYKVCSafeNSObject_Example' do
  pod 'SGYKVCSafeNSObject', :path => '../'

  target 'SGYKVCSafeNSObject_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
